package javaee.webstore.confighibernate;
// Generated Feb 19, 2022 8:34:39 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,schema="HR"
)
public class Users  implements java.io.Serializable {


     private BigDecimal userId;
     private String userName;
     private String userEmail;
     private String userAddress;
     private String userGender;
     private BigDecimal userExpYears;
     private Date userBirthDate;
     private Boolean userHasCar;
     private String userCountry;
     private String userPassword;

    public Users() {
    }

	
    public Users(BigDecimal userId) {
        this.userId = userId;
    }
    public Users(BigDecimal userId, String userName, String userEmail, String userAddress, String userGender, BigDecimal userExpYears, Date userBirthDate, Boolean userHasCar, String userCountry, String userPassword) {
       this.userId = userId;
       this.userName = userName;
       this.userEmail = userEmail;
       this.userAddress = userAddress;
       this.userGender = userGender;
       this.userExpYears = userExpYears;
       this.userBirthDate = userBirthDate;
       this.userHasCar = userHasCar;
       this.userCountry = userCountry;
       this.userPassword = userPassword;
    }
   
     @Id 

    
    @Column(name="USER_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    
    @Column(name="USER_NAME", length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="USER_EMAIL", length=100)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="USER_ADDRESS", length=100)
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    
    @Column(name="USER_GENDER", length=1)
    public String getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }

    
    @Column(name="USER_EXP_YEARS", precision=22, scale=0)
    public BigDecimal getUserExpYears() {
        return this.userExpYears;
    }
    
    public void setUserExpYears(BigDecimal userExpYears) {
        this.userExpYears = userExpYears;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="USER_BIRTH_DATE", length=7)
    public Date getUserBirthDate() {
        return this.userBirthDate;
    }
    
    public void setUserBirthDate(Date userBirthDate) {
        this.userBirthDate = userBirthDate;
    }

    
    @Column(name="USER_HAS_CAR", precision=1, scale=0)
    public Boolean getUserHasCar() {
        return this.userHasCar;
    }
    
    public void setUserHasCar(Boolean userHasCar) {
        this.userHasCar = userHasCar;
    }

    
    @Column(name="USER_COUNTRY", length=500)
    public String getUserCountry() {
        return this.userCountry;
    }
    
    public void setUserCountry(String userCountry) {
        this.userCountry = userCountry;
    }

    
    @Column(name="USER_PASSWORD", length=100)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }




}


