package javaee.webstore.jdbc.books;
// Generated Sep 6, 2019 11:57:05 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Base64;
import java.util.Date;
import javaee.webstore.jdbc.category.Category;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "BOOK", schema = "EBOOK", uniqueConstraints = @UniqueConstraint(columnNames = "BOOK_TITLE")
)
public class Book implements java.io.Serializable {

    private int bookId;
    private Category category;
    private String bookTitle;
    private String bookAuthor;
    private String bookDescription;
    private String bookISBN;
    private byte[] bookImage;
    private double bookPrice;
    private Date bookPublishDate;
    private Date lastUpdateTime;

   
    private String base64Image;
    
     public Book() {
    }

    public Book(int bookId, String bookTitle, String bookAuthor, String bookDescription, byte[] bookImage, String bookISBN, double bookPrice, Date bookPublishDate, Date lastUpdateTime, Category category) {
        this.bookId = bookId;
        this.bookTitle = bookTitle;
        this.bookAuthor = bookAuthor;
        this.bookDescription = bookDescription;
        this.bookImage = bookImage;
        this.bookISBN = bookISBN;
        this.bookPrice = bookPrice;
        this.bookPublishDate = bookPublishDate;
        this.lastUpdateTime = lastUpdateTime;
        this.category = category;
    }

    public Book(int bookId, String bookTitle, String bookAuthor, String bookDescription, String bookISBN, double bookPrice, Date bookPublishDate, Date lastUpdateTime,Category category) {
        this.bookId = bookId;
        this.bookTitle = bookTitle;
        this.bookAuthor = bookAuthor;
        this.bookDescription = bookDescription;
        this.bookISBN = bookISBN;
        this.bookPrice = bookPrice;
        this.bookPublishDate = bookPublishDate;
        this.lastUpdateTime = lastUpdateTime;
        this.category = category;
    }

    public Book(String bookTitle, String bookAuthor, String bookDescription, String bookISBN, double bookPrice, Date bookPublishDate, Date lastUpdateTime, Category category) {
        this.bookTitle = bookTitle;
        this.bookAuthor = bookAuthor;
        this.bookDescription = bookDescription;
        this.bookISBN = bookISBN;
        this.bookPrice = bookPrice;
        this.bookPublishDate = bookPublishDate;
        this.lastUpdateTime = lastUpdateTime;
        this.category = category;
    }

    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "BOOK_SEQ")
    @SequenceGenerator(name = "BOOK_SEQ", sequenceName = "BOOK_SEQ")
    @Column(name = "BOOK_ID", unique = true, nullable = false, precision = 6, scale = 0)
    public int getBookId() {
        return this.bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CATEGORY_ID")
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @Column(name = "BOOK_TITLE", unique = true, length = 128)
    public String getBookTitle() {
        return this.bookTitle;
    }

    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }

    @Column(name = "BOOK_AUTHOR", length = 64)
    public String getBookAuthor() {
        return this.bookAuthor;
    }

    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor;
    }

    @Column(name = "BOOK_DESCRIPTION", length = 100)
    public String getBookDescription() {
        return this.bookDescription;
    }

    public void setBookDescription(String bookDescription) {
        this.bookDescription = bookDescription;
    }

    @Column(name = "BOOK_ISBN", length = 15)
    public String getBookISBN() {
        return this.bookISBN;
    }

    public void setBookISBN(String bookISBN) {
        this.bookISBN = bookISBN;
    }

    @Column(name = "BOOK_IMAGE")
    public byte[] getBookImage() {
        return this.bookImage;
    }

    public void setBookImage(byte[] bookImage) {
        this.bookImage = bookImage;
    }

    @Column(name = "BOOK_PRICE", precision = 8)
    public double getBookPrice() {
        return this.bookPrice;
    }

    public void setBookPrice(double bookPrice) {
        this.bookPrice = bookPrice;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "BOOK_PUBLISH_DATE", length = 7)
    public Date getBookPublishDate() {
        return this.bookPublishDate;
    }

    public void setBookPublishDate(Date bookPublishDate) {
        this.bookPublishDate = bookPublishDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LAST_UPDATE_TIME", length = 7)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @Transient
        public String getBase64Image() {
           this.base64Image = Base64.getEncoder().encodeToString(this.bookImage);
        return base64Image;
    }

    public void setBase64Image(String base64Image) {
        this.base64Image = base64Image;
    }
  
}
