package javaee.webstore.jdb.testH;
// Generated Feb 9, 2022 8:42:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductsDetails generated by hbm2java
 */
public class ProductsDetails  implements java.io.Serializable {


     private BigDecimal productDetailId;
     private BigDecimal productPrice;
     private String productDesc;
     private Set productses = new HashSet(0);

    public ProductsDetails() {
    }

	
    public ProductsDetails(BigDecimal productDetailId) {
        this.productDetailId = productDetailId;
    }
    public ProductsDetails(BigDecimal productDetailId, BigDecimal productPrice, String productDesc, Set productses) {
       this.productDetailId = productDetailId;
       this.productPrice = productPrice;
       this.productDesc = productDesc;
       this.productses = productses;
    }
   
    public BigDecimal getProductDetailId() {
        return this.productDetailId;
    }
    
    public void setProductDetailId(BigDecimal productDetailId) {
        this.productDetailId = productDetailId;
    }
    public BigDecimal getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }
    public String getProductDesc() {
        return this.productDesc;
    }
    
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


