package javaee.webstore.jdb.testH;
// Generated Feb 9, 2022 8:42:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Software generated by hbm2java
 */
public class Software  implements java.io.Serializable {


     private BigDecimal softwareId;
     private Products products;
     private String softwareName;

    public Software() {
    }

	
    public Software(BigDecimal softwareId) {
        this.softwareId = softwareId;
    }
    public Software(BigDecimal softwareId, Products products, String softwareName) {
       this.softwareId = softwareId;
       this.products = products;
       this.softwareName = softwareName;
    }
   
    public BigDecimal getSoftwareId() {
        return this.softwareId;
    }
    
    public void setSoftwareId(BigDecimal softwareId) {
        this.softwareId = softwareId;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getSoftwareName() {
        return this.softwareName;
    }
    
    public void setSoftwareName(String softwareName) {
        this.softwareName = softwareName;
    }




}


