package javaee.webstore.jdb.testH;
// Generated Feb 9, 2022 8:42:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private BigDecimal userId;
     private String userName;
     private String userEmail;
     private String userAddress;
     private String userGender;
     private BigDecimal userExpYears;
     private Date userBirthDate;
     private Boolean userHasCar;
     private String userCountry;
     private String userPassword;

    public Users() {
    }

	
    public Users(BigDecimal userId) {
        this.userId = userId;
    }
    public Users(BigDecimal userId, String userName, String userEmail, String userAddress, String userGender, BigDecimal userExpYears, Date userBirthDate, Boolean userHasCar, String userCountry, String userPassword) {
       this.userId = userId;
       this.userName = userName;
       this.userEmail = userEmail;
       this.userAddress = userAddress;
       this.userGender = userGender;
       this.userExpYears = userExpYears;
       this.userBirthDate = userBirthDate;
       this.userHasCar = userHasCar;
       this.userCountry = userCountry;
       this.userPassword = userPassword;
    }
   
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }
    public BigDecimal getUserExpYears() {
        return this.userExpYears;
    }
    
    public void setUserExpYears(BigDecimal userExpYears) {
        this.userExpYears = userExpYears;
    }
    public Date getUserBirthDate() {
        return this.userBirthDate;
    }
    
    public void setUserBirthDate(Date userBirthDate) {
        this.userBirthDate = userBirthDate;
    }
    public Boolean getUserHasCar() {
        return this.userHasCar;
    }
    
    public void setUserHasCar(Boolean userHasCar) {
        this.userHasCar = userHasCar;
    }
    public String getUserCountry() {
        return this.userCountry;
    }
    
    public void setUserCountry(String userCountry) {
        this.userCountry = userCountry;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }




}


